name: Image scan

on:
    workflow_call:


jobs:
    image_scan:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: login to docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Trivy vulnerability scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: ${{ vars.DOCKERHUB_USER }}/todo_remember:latest
                format: table
                severity: 'CRITICAL,HIGH'
                exit-code: '1'